#端口
server:
  port: 8771
#服务应用名
spring:
  application:
    name: dashboard-b
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&useSSL=true
    password: 123456
    username: root
  redis:
    host: 192.168.199.222
    port: 6379
    database: 0
    password: root
  rabbitmq:
    host: 81.68.111.61
    username: admin
    password: admin
    port: 5672
    virtual-host: my_vhost
  mail:
    username: 1223240795@qq.com
    password: nxknpdvriggmjgfj
    host: smtp.qq.com
#    properties:
#      main:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true



eureka:
  instance:
    #使用ip代替实例名
    prefer-ip-address: true
    #实例的主机名
    hostname: ${spring.cloud.client.ip-address}
    # 实例的 ID 规则
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    service-url:
      #注册中心
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



